
# Site settings
title: StreamVista
description: Premium streaming experience for movies, TV shows, and anime
theme: jekyll-theme-primer

# GitHub Pages settings
markdown: kramdown
baseurl: ""
url: ""
